"""Initial migration

Revision ID: 698e732dfd98
Revises: 
Create Date: 2024-11-27 19:58:01.433800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698e732dfd98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=True),
    sa.Column('descricao', sa.String(length=256), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('imagem', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('senha', sa.String(length=128), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('rua', sa.String(length=128), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('cidade', sa.String(length=64), nullable=True),
    sa.Column('codigo_postal', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    op.drop_table('user')
    op.drop_table('product')
    # ### end Alembic commands ###
